# Generated by Django 6.0.3 on 2026-03-29 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('grupo', 'Fase de Grupos'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('terceiro', 'Disputa de 3º Lugar'), ('final', 'Final')], default='grupo', max_length=20, verbose_name='Fase')),
                ('round_number', models.IntegerField(default=1, verbose_name='Rodada')),
                ('match_number', models.IntegerField(default=1, verbose_name='Número da Partida')),
                ('score_a', models.IntegerField(default=0, verbose_name='Sets Jogador A')),
                ('score_b', models.IntegerField(default=0, verbose_name='Sets Jogador B')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada')], default='pendente', max_length=20, verbose_name='Status')),
                ('next_match_slot', models.CharField(blank=True, choices=[('A', 'Slot A'), ('B', 'Slot B')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='championships.championship', verbose_name='Campeonato')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='championships.group', verbose_name='Grupo')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='matches.match', verbose_name='Próxima Partida')),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='players.player', verbose_name='Jogador A')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='players.player', verbose_name='Jogador B')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='players.player', verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['round_number', 'match_number'],
            },
        ),
    ]
