# Generated by Django 6.0.3 on 2026-03-29 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes', 'Inscrições Abertas'), ('fase_grupos', 'Fase de Grupos'), ('eliminatorias', 'Fase Eliminatória'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='championships.championship', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('sets_won', models.IntegerField(default=0)),
                ('sets_lost', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='championships.group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='players.player')),
            ],
            options={
                'verbose_name': 'Classificação do Grupo',
                'verbose_name_plural': 'Classificações dos Grupos',
                'ordering': ['-points', '-sets_won', 'sets_lost'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0, verbose_name='Seed')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='championships.championship', verbose_name='Campeonato')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='players.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['seed'],
                'unique_together': {('championship', 'player')},
            },
        ),
        migrations.CreateModel(
            name='GroupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slots', to='championships.group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slots', to='players.player')),
            ],
            options={
                'unique_together': {('group', 'player')},
            },
        ),
    ]
