# Generated by Django 6.0.3 on 2026-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='data_fim',
        ),
        migrations.AlterField(
            model_name='championship',
            name='data_inicio',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
