# Generated by Django 6.0.3 on 2026-03-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_remove_championship_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='status',
        ),
        migrations.AddField(
            model_name='championship',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
